project_id = "crugiszdfjruvdsqdnha"

[functions.delete-user]
verify_jwt = false

[functions.suggest-producao]
verify_jwt = false

[functions.create-factory-owner]
verify_jwt = false

[functions.delete-factory]
verify_jwt = false
